# This file contains the essential configs for the ingress controller helm chart

################################################################################
# Specify which application gateway the ingress controller will manage
#
appgw:
    subscriptionId: 4e1a2fb0-7ff7-4dfc-89dd-55e8a7647486
    resourceGroup: rg-agw-aks-demo
    name: gateway-agw-aks-demo

################################################################################
# Specify which kubernetes namespace the ingress controller will watch
# Default value is "default"
#
# kubernetes:
#   watchNamespace: <namespace>

################################################################################
# Specify the authentication with Azure Resource Manager
#
# Two authentication methods are available:
# - Option 1: AAD-Pod-Identity (https://github.com/Azure/aad-pod-identity)
# - Option 2: ServicePrincipal as a kubernetes secret
# armAuth:
#   type: servicePrincipal
#   secretName: networking-appgw-k8s-azure-service-principal
#   secretKey: ServicePrincipal.json
armAuth:
    type: aadPodIdentity
    identityResourceID: /subscriptions/4e1a2fb0-7ff7-4dfc-89dd-55e8a7647486/resourcegroups/MC_rg-agw-aks-demo_k8s-cluster-agw-aks-demo_westus/providers/Microsoft.ManagedIdentity/userAssignedIdentities/agw-aks-demo-user
    identityClientID:  635fe4b5-401d-46dc-80bd-f7a95c41ea21

rbac:
    enabled: false

aksClusterConfiguration:
    apiServerAddress: k8s-cluster-agw-aks-demo-3dbef796.hcp.westus.azmk8s.io